EV_chargers/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns (
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('users/', include('users.urls')),
    path('map/', include('yandex_maps_ev.urls')),
    path('rent/', include('EV_rent.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

EV_rent/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CarList.as_view(), name='rent'),
    path('service_request/', views.service_request, name='service_request'),
    path('rental_request/<int:car_id>', views.rental_request, name='rental_request'),
    path('service_request_success/', views.service_request_success, name='service_request_success'),
    path('<slug:slug>/', views.ModelDetailView.as_view(), name='model_info'),
]

users/urls.py
from django.urls import path, include
from users.views import Register, profile

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("register/", Register.as_view(), name='register'),
    path("profile/", profile, name='profile'),
]

EV_rent/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from datetime import datetime

from users.models import User


# Электромобили (ид, Модель, Тип зарядки, кол-во л.с., сидячих мест, цена аренды)

class Car(models.Model):
    car_full_name = models.CharField(max_length=100)
    car_brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    charge_type = models.CharField(max_length=100)
    horse_power = models.IntegerField()
    num_sits = models.IntegerField()
    range_km = models.IntegerField()
    rent_price = models.DecimalField(max_digits=5, decimal_places=2)
    year = models.IntegerField()
    image = models.ImageField(upload_to='image_cars', blank=True, null=True)
    description = models.TextField()
    url_page = models.SlugField(max_length=50, unique=True)
    is_broken = models.BooleanField(default=False)
    is_rented = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("model_info", kwargs={"slug": self.url_page})

    def __str__(self):
        return f"{self.car_brand} {self.model}"


class ServiceRequest(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    car_model = models.ForeignKey(Car, on_delete=models.CASCADE)
    description = models.TextField()
    photos = models.ImageField(upload_to='repair_images/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f"{self.person.first_name} {self.person.last_name} сообщил о поломке {self.car_model}"


class RentalRequest(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    car_model = models.ForeignKey(Car, on_delete=models.CASCADE)
    num_days = models.IntegerField()

    def __str__(self):
        return f"{self.person.first_name} {self.person.last_name} арендовал {self.car_model}"

class RentalHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    start_date = models.DateTimeField(default=datetime.now, blank=True)
    end_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}, аренда {self.car} от {self.start_date.strftime('%Y-%m-%d')}"
class ServiceHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True)
    description = models.TextField()

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}, поломка {self.car} от {self.date.strftime('%Y-%m-%d')}"



@receiver(pre_delete, sender=RentalRequest)
def set_car_rent_as_available(sender, instance, **kwargs):
    car = instance.car_model
    car.is_rented = False
    car.save()


@receiver(pre_delete, sender=ServiceRequest)
def set_car_broken_as_available(sender, instance, **kwargs):
    car = instance.car_model
    car.is_broken = False
    car.save()

EV_rent/forms.py
from django import forms
from .models import Car, ServiceRequest, RentalRequest
from users.models import User

# class ServiceRequestForm(forms.Form):
#     first_name = forms.CharField(max_length=100)
#     last_name = forms.CharField(max_length=100)
#     email = forms.EmailField()
#     #car_model = forms.ModelChoiceField(queryset=Car.objects.all())
#     car_model = forms.CharField(max_length=100)
#     description = forms.CharField(widget=forms.Textarea)
#     photos = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))


class ServiceRequestForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['car_model', 'description', 'photos']


    person = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())
    car_model = forms.ModelChoiceField(queryset=Car.objects.filter(is_broken=False))
    photos = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))


class RentalRequestForm(forms.ModelForm):
    class Meta:
        model = RentalRequest
        fields = ['num_days']

    person = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())
    # car_model = forms.ModelChoiceField(queryset=Car.objects.filter(is_rented=False))

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.utils.translation import gettext_lazy as _

User = get_user_model()

class UserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"})
    )

    driver_license = forms.ImageField(required=True, widget=forms.ClearableFileInput(attrs={'multiple': False}))
    driver_license_with_owner = forms.ImageField(required=True, widget=forms.ClearableFileInput(attrs={'multiple': False}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = {"username", "email", "driver_license", "driver_license_with_owner"}


class UserUpdateForm(UserChangeForm):
    password = None
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', ]
        exclude = ('publisher',)
        # widgets = {
        #     'username': forms.TextInput(attrs={'readonly': 'readonly'}),
        #     'email': forms.TextInput(attrs={'readonly': 'readonly'})
        # }

#
# class UserUpdateForm(forms.ModelForm):
#     email = forms.EmailField(
#         label=_("Email"),
#         max_length=254,
#         widget=forms.EmailInput(attrs={"autocomplete": "email"})
#     )
#
#     class Meta(UserCreationForm.Meta):
#         model = User
#         fields = {"username", "email", "first_name", "last_name"}

EV_rent/views.py
from django.shortcuts import render, redirect
from .models import Car, ServiceRequest, RentalRequest, RentalHistory, ServiceHistory
from .forms import ServiceRequestForm, RentalRequestForm
from django.views.generic import ListView, DetailView
from users.models import User

from datetime import datetime, timedelta


class CarList(ListView):
    model = Car
    queryset = Car.objects.all()
    # здесь template_name = "EV_rent/car_list.html" по умолчанию, так как django ищет html с ИМЯ-МОДЕЛИ_list.html
    context_object_name = "cars"

class ModelDetailView(DetailView):
    model = Car
    slug_field = "url_page"
    # здесь template_name = "EV_rent/car_detail.html" по умолчанию, так как django ищет html с ИМЯ-МОДЕЛИ_detail.html


def service_request(request):
    if request.method == 'POST':
        form = ServiceRequestForm(request.POST, request.FILES)

        if form.is_valid():
            service_request = form.save(commit=False)  # Создаем объект, но не сохраняем его в БД
            service_request.person = request.user  # Указываем пользователя в поле person
            service_request.save()

            car_model = service_request.car_model
            car = Car.objects.get(car_full_name=car_model)
            car.is_broken = True
            car.save()

            ServiceHistory.objects.create(user=request.user, car=car, description=service_request.description)

            return redirect('service_request_success')
    else:
        form = ServiceRequestForm()
    return render(request, 'EV_rent/service_request.html', {'form': form})


def service_request_success(request):
    return render(request, 'EV_rent/service_request_success.html')


def rental_request(request, car_id):
    car = Car.objects.get(pk=car_id)
    if request.method == 'POST':
        form = RentalRequestForm(request.POST)

        if form.is_valid():
            rental_request = form.save(commit=False)  # Создаем объект, но не сохраняем его в БД
            rental_request.person = request.user  # Указываем пользователя в поле person


            rental_request.car_model = car
            rental_request.save()

            car.is_rented = True
            car.save()

            RentalHistory.objects.create(user=request.user, car=car, start_date=datetime.now(), end_date=(datetime.now() + timedelta(days=rental_request.num_days)))

            return redirect('service_request_success')
    else:
        form = RentalRequestForm()
    return render(request, 'EV_rent/rental_request.html', {'form': form, 'car': car})


def rental_request_success(request):
    return render(request, 'EV_rent/service_request_success.html')

EV_rent/templates/EV_rent/rental_request.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{#ДОБАВИТЬ ОТОБРАЖЕНИЕ ЦЕНЫ ДЛЯ АРЕНДЫ: ЦЕНА * ДНИ#}

{% block title %} {% trans 'Rental Request' %} {% endblock %}

{% block meta %}
    {% if not user.is_authenticated %}
        <meta http-equiv="refresh" content="3;URL={% url 'login' %}"/>
    {% endif %}
{% endblock %}

{% block style_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    {% if user.is_authenticated %}
        <link rel="stylesheet" type='text/css' href="{% static 'users/css/sign_css.css' %}">
    {% endif %}
{% endblock %}

{% block cnt %}
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="offset-md-4 col-md-4 offset-sm-3 col-sm-6">
                <div class="form-container">
                    <h3 class="title">{% trans "Rental Request" %} - {{ car.car_full_name }}</h3>

                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="person" value="{{ user.pk }}">
                        <input type="hidden" id="price" name="price" value="{{ car.rent_price }}">
                        {#                        <div class="form-group">#}
                        {#                            <input class="form-control" type="text" name="first_name" id="id_first_name"#}
                        {#                                   placeholder="First Name" value={{ person.first_name }}>#}
                        {#                        </div>#}
                        {#                        <div class="form-group">#}
                        {#                            <input class="form-control" type="text" name="last_name" id="id_last_name"#}
                        {#                                   placeholder="Last Name" value={{ person.last_name }}>#}
                        {#                        </div>#}
                        {#                        <div class="form-group">#}
                        {#                            <input class="form-control" type="email" name="email" id="id_email" placeholder="Person"#}
                        {#                                   value={{ person.email }}>#}
                        {#                        </div>#}
                        <div class="form-group">
                            <span class="description"
                                  style="text-align: left; margin-bottom: 0">{% trans 'First Name' %}:</span>
                            <p class="form-control"
                               style="text-align: left; cursor: pointer; font-size: 17px">{{ user.first_name }}</p>
                        </div>

                        <div class="form-group">
                            <span class="description" style="text-align: left; margin-bottom: 0">{% trans 'Last Name' %}:</span>
                            <p class="form-control"
                               style="text-align: left; cursor: pointer; font-size: 17px">{{ user.last_name }}</p>
                        </div>

                        <div class="form-group">
                            <span class="description" style="text-align: left; margin-bottom: 0">E-mail:</span>
                            <p class="form-control"
                               style="text-align: left; cursor: pointer; font-size: 17px">{{ user.email }}</p>
                        </div>

                        <div class="form-group">
                            <label for="id_num_days" class="description"
                                   style="text-align: left; margin-bottom: 0">{% trans 'Number of Days' %}:</label>
                            <input class="form-control" type="number" id="id_num_days" name="num_days" min="1" max="30"
                                   placeholder="{% trans 'Number of Days' %}" style=" font-size: 17px">
                        </div>

                        <div class="form-group">
                            <label for="total-price" class="description"
                                   style="text-align: left; margin-bottom: 0">{% trans 'Total Cost' %}:</label>
                            <div class="input-group">
                                <div class="input-group-text"
                                     style="background: #F7F8F9; border: 2px solid #eef0f1; color: #4E4C97; font-size: 16px">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                         class="bi bi-cash-coin" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                              d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                                        <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                                        <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                                        <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                                    </svg>
                                </div>
                                <input class="form-control" type="text" id="total-price" name="total_price" readonly
                                       style="text-align: left; cursor: pointer; font-size: 17px; margin-bottom: 0; padding-left: 5px">
                            </div>


                            <p class="description">{% trans 'Your discount is' %}: <span id="discount"></span></p>
                        </div>

                        <button type="submit" class="btn signup">Submit</button>
                    </form>
                </div>
            </div>
        </div>

    {% else %}

        <p style="height: 700px; margin-top: 300px; font-size: 34px; text-align: center">
            {% trans 'You are not authorized! You will be redirected to the login page..' %}
        </p>

    {% endif %}

{% endblock %}

{% block script %}
    <script>
        // Получаем элементы формы
        const priceInput = document.getElementById('price');
        const rentalDaysInput = document.getElementById('id_num_days')
        const totalPriceInput = document.getElementById('total-price');
        const discountLabel = document.getElementById('discount');

        // Функция для вычисления и обновления значения Total Price
        function updateTotalPrice() {
            const price = parseFloat(priceInput.value.replace(',', '.'));
            let rentalDays = isNaN(parseInt(rentalDaysInput.value)) ? '' : parseInt(rentalDaysInput.value);
            let totalPrice;
            let discount;

            //Ограничение ввода количества дней
            if (rentalDays > 30) {
                rentalDays = 30;
            }
            rentalDaysInput.value = rentalDays;

            console.log(rentalDays)

            //Присваивание скидки и вычисленние итоговой стоимости
            if (!rentalDays) {
                totalPrice = ''
                discount = ''
            }
            else if (rentalDays >= 1 && rentalDays < 5) {
                totalPrice = (price * rentalDays);
                discount = '0%'
            } else if (rentalDays >= 5 && rentalDays < 10) {
                totalPrice = ((price - price * 0.1) * rentalDays) * 0.9;
                discount = '10%'
            } else if (rentalDays >= 10 && rentalDays < 20) {
                totalPrice = (price * rentalDays) * 0.75;
                discount = '25%'
            } else if (rentalDays >= 20 && rentalDays < 31) {
                totalPrice = (price * rentalDays) * 0.5;
                discount = '50%'
            }

            totalPriceInput.value = totalPrice !== ''?totalPrice.toFixed(2) + ' BYN':'';
            discountLabel.innerHTML = discount
        }

        // Обновляем значение Total Price при изменении значений в полях Price и Rental Days
        priceInput.addEventListener('input', updateTotalPrice);
        rentalDaysInput.addEventListener('input', updateTotalPrice);
    </script>
{% endblock %}

EV_rent/templates/EV_rent/service_request.html
{% extends 'base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block title %} {% trans 'Service Request' %} {% endblock %}

{% block meta %}
    {% if not user.is_authenticated %}
        <meta http-equiv="refresh" content="3;URL={% url 'login' %}"/>
    {% endif %}
{% endblock %}

{% block style_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% if user.is_authenticated %}
        <link rel="stylesheet" type='text/css' href="{% static 'users/css/sign_css.css' %}">
    {% endif %}
{% endblock %}

{% block cnt %}

    {% if user.is_authenticated %}
        <div class="container-fluid">

            <div class="offset-md-4 col-md-4 offset-sm-3 col-sm-6">
                <div class="form-container">
                    <h3 class="text" style="color: #4E4C97">{% trans "Service Request" %}</h3>

                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="person" value="{{ user.pk }}">

                        <div class="form-group">
                            <span class="description" style="text-align: left">{% trans "Choose car" %}:</span>
                            {% render_field form.car_model|add_class:"form-control" placeholder="Car Model" %}
                        </div>
                        <div class="form-group">
                            {% render_field form.description|add_class:"form-control" placeholder="Description" %}
                        </div>
                        <div class="form-group">
                            {% render_field form.photos|add_class:"form-control" placeholder="Photos" %}
                        </div>

                        {#                  ВРЕМЕННО!!!!!!!!!!!!!!!!!!!!!!!!#}
                        <span class="description">{{ form.errors }}</span>

                        <button type="submit" class="btn signup">{% trans "Submit" %}</button>
                    </form>
                </div>
            </div>

        </div>

    {% else %}

        <p style="height: 700px; margin-top: 300px; font-size: 34px; text-align: center">
            {% trans 'You are not authorized! You will be redirected to the login page..' %}
        </p>

    {% endif %}

{% endblock %}

EV_rent/templates/EV_rent/service_request_success.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} {% trans "Service Request Submitted" %} {% endblock %}

{% block cnt %}
  <h1>{% trans "Service Request Submitted" %}</h1>
{% endblock %}